#!/bin/bash

PATH+=:$HOME/.path
PATH+=:$HOME/go/bin
PATH+=:$HOME/gbx/guapi-can/path
PATH+=:$HOME/npm-global/bin
export PATH

export GOPATH=$HOME/go
export GOROOT=/opt/go

# Continue only for 'normal' terminal
[ -z "$PS1" ] && return

source /etc/bash_completion

export HISTCONTROL=ignoredups:erasedups

shopt -s expand_aliases
stty -ixon # Disable ctrl+s freeze thing, use it for history search

#set -o vi # Vim line editing

alias ls="ls --color=auto"
alias ll="ls -la"
alias grep="grep --color=auto"
alias less="less -S"
alias gitg="setsid gitg > /dev/null 2>&1" 

for f in $(ls ~/common/bashrc.d); do
	source ~/common/bashrc.d/$f
done

if [ -f $HOME/.bashrc-local ]; then
	source $HOME/.bashrc-local
fi


