#!/bin/bash

while read r; do
	if [ -n "$r" ]; then
		cd $r
		git_status=$(git status 2> /dev/null)

		if [[ ! $git_status =~ "working directory clean" ]]; then
			echo "FIX $r"
			gitg
		elif [[ $git_status =~ "Your branch is ahead of" ]]; then
			git config --get remote.origin.url
			echo -e "PUSH $r \n [y/n]? "
			read resp < /dev/tty
			if [ "$resp" == "y" ]; then
				git push
			fi
		elif [[ $git_status =~ "nothing to commit" ]]; then
			echo "OK $r"
		fi
	fi
done < ~/git_repos
