#!/bin/bash


displays=$(xrandr | grep " connected" | cut -d' ' -f1 | sort | paste -sd ',' -)

case $displays in
	"DP3,DP4,eDP1")
		xrandr --output DP4 --auto
		xrandr --output DP3 --auto --right-of DP4
		xrandr --output eDP1 --off
		i3l=DP4
		i3r=DP3
		;;
	"eDP1,HDMI1,VGA1")
		xrandr --output HDMI1 --auto
		xrandr --output VGA1 --auto --right-of HDMI1
		xrandr --output eDP1 --off
		i3l=HDMI1
		i3r=VGA1
		;;
	*)
		for d in $(xrandr | grep " connected" | cut -d' ' -f1); do
			xrandr --output $d --auto
		done
		;;
esac
d="# AUTO GENERATED #"
d="$d\nworkspace 1 output $i3l"
d="$d\nworkspace 2 output $i3l"
d="$d\nworkspace 3 output $i3l"
d="$d\nworkspace 4 output $i3l"
d="$d\nworkspace 5 output $i3l"

d="$d\nworkspace 6 output $i3r"
d="$d\nworkspace 7 output $i3r"
d="$d\nworkspace 8 output $i3r"
d="$d\nworkspace 9 output $i3r"
d="$d\nworkspace 10 output $i3r"

echo -e $d > ~/.i3/conf.d/displays
cat ~/.i3/conf.d/* > ~/.i3/config
i3-msg reload
